Product.delete_all

product1 = Product.create(name: 'Chainsaw', category: 'Tools', stocked: true , price: 240.75 )
product2 = Product.create(name: 'Grinder', category: 'Tools', stocked: true , price: 120.35 )
product3 = Product.create(name: 'Ruler', category: 'Tools', stocked: false , price: 18.50 )
product4 = Product.create(name: 'Drill', category: 'Tools', stocked: true , price: 155.55 )
product5 = Product.create(name: 'iPad', category: 'Electronics', stocked: false , price: 415.00 )
product6 = Product.create(name: 'MacBook Pro', category: 'Electronics', stocked: true , price: 1995.25 )
product7 = Product.create(name: 'iMac', category: 'Electronics', stocked: true , price: 2243.50 )
product8 = Product.create(name: 'iPhone', category: 'Electronics', stocked: true , price: 899.99 )
product9 = Product.create(name: 'Skillet', category: 'Kitchen', stocked: true , price: 30.75 )
product10 = Product.create(name: 'Football', category: 'Sports', stocked: false , price: 10.75 )
product11 = Product.create(name: 'Running tights', category: 'Sports', stocked: true , price: 78.70 )
product12 = Product.create(name: 'Soup-ladle', category: 'Kitchen', stocked: true , price: 12.75 )
product13 = Product.create(name: 'Ref whistle', category: 'Sports', stocked: true , price: 5.55 )
product14 = Product.create(name: 'Red dress', category: 'Clothing', stocked: true , price: 223.25 )
product15 = Product.create(name: 'Black flats', category: 'Clothing', stocked: true , price: 122.25 )
product16 = Product.create(name: 'Sun hat', category: 'Clothing', stocked: false , price: 12.75 )
product17 = Product.create(name: 'Sandwich waffle', category: 'Kitchen', stocked: true , price: 23.55 )
product18 = Product.create(name: 'Kitchen timer', category: 'Kitchen', stocked: false , price: 9.25 )
product19 = Product.create(name: 'Potholder', category: 'Kitchen', stocked: true , price: 2.75 )
